In [1]:
# Import pandas to load data
import pandas as pd

# Import function from SleePy to estimate sleep duration
from sleepy import estimate_sleep

# Load data
data = pd.read_csv('/home/haalbers/dissertation/mobiledna-clean.csv', usecols = ['id','startTime','endTime'], nrows = 2000)

# Estimate sleep duration
estimate_sleep(data)

             id        date  sleep duration
0   User #15444  2020-01-29        7.236067
1   User #15444  2020-01-30        8.555471
2   User #15444  2020-01-31        8.646156
3   User #15444  2020-02-01        8.099817
4   User #15444  2020-02-02        8.511842
5   User #15444  2020-02-03        7.964478
6   User #15444  2020-02-04        8.615214
7   User #15444  2020-02-05        6.612968
8   User #15444  2020-02-06        7.759046
9   User #15444  2020-02-07        8.532245
10  User #15444  2020-02-08        8.588606
11  User #15444  2020-02-09        8.226761